{% set name = "sphinx-copybutton" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0c059daadd03c27ba750da534a92a63e7a36a7736dcf684f26ee346199787f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - sphinx >=1.8
  run:
    - python >=3
    - sphinx >=1.8

test:
  imports:
    - sphinx_copybutton

about:
  home: https://github.com/executablebooks/sphinx-copybutton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small sphinx extension to add a "copy" button to code blocks.

extra:
  recipe-maintainers:
    - hmaarrfk
    - choldgraf
