{% set name = "sphinx-copybutton" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9492883786984b6179c92c07ab0410237b26efa826adfa792acfd17b91a63e5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - sphinx
    - flit
  run:
    # building needs python 3, but apparently can run on python 2
    - python
    - sphinx

test:
  imports:
    - sphinx_copybutton

about:
  home: https://github.com/choldgraf/sphinx-copybutton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small sphinx extension to add a "copy" button to code blocks.

extra:
  recipe-maintainers:
    - hmaarrfk
