{% set name = "sphinx-copybutton" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3695987d5e98e3b223471aaed8aa7491e03e9bfc48ed655a91446fd5e30b6c25

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - sphinx >=1.8
  run:
    - python >=3
    - sphinx >=1.8

test:
  imports:
    - sphinx_copybutton

about:
  home: https://github.com/executablebooks/sphinx-copybutton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small sphinx extension to add a "copy" button to code blocks.

extra:
  recipe-maintainers:
    - hmaarrfk
    - choldgraf
    - chrisjsewell
