{% set name = "sphinx-copybutton" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e0461df394515284e3907e3f418a0c60ef6ab6c9a27a800c8552772d0a402a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - sphinx >=1.8
  run:
    # building needs python 3, but apparently can run on python 2
    - python
    - sphinx >=1.8

test:
  imports:
    - sphinx_copybutton

about:
  home: https://github.com/executablebooks/sphinx-copybutton
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small sphinx extension to add a "copy" button to code blocks.

extra:
  recipe-maintainers:
    - hmaarrfk
    - choldgraf
    - chrisjsewell
