travis:
  secure:
    BINSTAR_TOKEN: H/TFumFuMimTBiOwomATU59MD9IexhUMhCZRD1A94k3JPTrwmlxv6UjShkPwJQO248fD3RQGA2WRSkF9MdjZQXIIorXcUBRv3IFiOyATCV4GBLFSVXDXHW5QdqnZ6gSj4M415xkTWYhrv6EXWj8aK77S7152XEgQhKOqY3cDG6CZsDdYVkZkLqQJvND5UKsKaixAT31g4dD/je1PTpnqc9Lx1BdLggPkMlP0RaXNQyoR9TKhulC++kbC/Qx+uaEogXqJlWWX+lHuQesQmnWF92THYbJIhYsElWUmM2Rcll9//hWhU21RtSc9maNk1aFSKpyl67cfpbY0pfWS3bqu5LU1/gq5VSopHlwsWfbMyUODCwx3Y5VyQgyEetG25z+uNCI5m7c+lrRyBUKWuAlDbrZtFEISuwdC6l4nwNSOnzC7qSZjxesEH4665R0rLELU9DV9CVszTNOAeMU29b4881q7OQCBtXHSKGZGfXpDOqRHdLWLjn0XNSs4PxyXTyecOTcGY0jLfvIouuxw0+kB6FXviQtYc5dbaZYK9G6V9jb0ga5ARX+yyJirRVT1CTCqLA0sQDey6Fi0QUcudgxcRO5Jkww0sWqukd6PZ+A9KD6jPk+HWj7iUO2EpBqEUnyEC7MqLsK7ZOGar7BW0xSY9aPv8mByOrNC5JqciKeC/mI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
